### ISSUE TITLE
Offender Data for Application Development

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#1]
### Summary

- [x] Obtain geocoded offender data from agrc sftp
  - data are updated each morning by about 7 a.m.
- [ ] Obtain lookup data from [drive sheet](https://docs.google.com/spreadsheets/d/1qE7BFMH5xTmvQ9-H8Yo16SwZNxAqBAlgRaG1HFIIbAU/edit#gid=1065322794)
- [x] Add forklift process to pull data each day (even though dev data may not change through application development)

**Comment by steveoh** [comment]
Is this an action item or informational? If its purpose is informational, I would put it in a wiki or a readme.md

**Comment by steveoh** [comment]
the lookup data wiki link is broken @nathankota.
