### ISSUE TITLE
Filter Category - Offender

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#10]
### Summary
As a user, I would like to have a filter category called "Offender" that I can click an icon to expand the filters within that category, and select which filters I want to apply.

#### Name
  - [ ] start typing to get hints; first or last name
  - ofndr_full_name
#### ~~Location~~
  - ~~ofndr_location~~
- _(removed during 6/10/19 meeting)_
#### Gender
  - [x] gender
#### ~~Age~~
  - ~~single value or range of values~~
  - ~~dob ---> (today-dob)/365.25 = age~~
  - _(removed during 6/10/19 meeting)_
#### Phone
  - [ ] ofndr_phone
  - format is changing to remove phone time prefix
#### Employer
  - [ ] employer

**Comment by steveoh** [comment]
what does the location part of this filter look like?

**Comment by steveoh** [comment]
current mock up
![image](https://user-images.githubusercontent.com/325813/58998007-13f5fb80-87bc-11e9-9503-749dadaf9e0c.png)
