### ISSUE TITLE
Filter Category - Other

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#11]
### Summary
As a user, I would like to have a filter category called "Other" that I can click an icon to expand the filters within that category, and select which filters I want to apply.

#### Legal Status
- [x] Probation and Parole
- [x] legal_stat_type
#### Standard of Supervision
- [x] low, mod, high, int, no std
- [x] no std indicated by null value in std_of_sprvsn
- [x] nulls (no std) should always be returned by filter, regardless of selection
#### Special Supervision
- [x] drop-down to display [Group Title](https://docs.google.com/spreadsheets/d/1iuZQkhIVfoH7x0BeaZMHMuCEaqadWCJSnX5knxTl6z4/edit?ts=5d081993#gid=705257935) values
- [x] button next to each value to toggle on/off, similar to phone app settings
- [x] by default, filter excludes values with EX on the [sheet](https://docs.google.com/spreadsheets/d/1iuZQkhIVfoH7x0BeaZMHMuCEaqadWCJSnX5knxTl6z4/edit?ts=5d081993#gid=705257935)
- [x] "All" option to select all values, including EX
- [x] "Default" option to return to default (excluding EX)
#### Gang Name
- [x] search by stg_typ
- [x] multi-select
#### Offense Type
- [x] search by ofnse_typ_desc
- [x] display [selections](https://github.com/agrc/parole-and-probation/wiki/Lookup-Data#offense-type) in alphabetical order
- [x] multi-select
#### Active Warrant
- [x] active_warrant (yes/no)

**Comment by steveoh** [comment]
current mockup
![image](https://user-images.githubusercontent.com/325813/58998067-4d2e6b80-87bc-11e9-8884-dcd2d52a618d.png)

**Comment by nathankota** [comment]
No Field Visit removed from this and added to #12. The github issues were updated to match jira issues since we were going to use jira for this project, until we decided against it last week.

**Comment by steveoh** [comment]
Will you make the filter removal a new issue so we don't need to dig into comments and edit history

**Comment by nathankota** [comment]
> Will you make the filter removal a new issue so we don't need to dig into comments and edit history

will be resolved by #27

**Comment by nathankota** [comment]
Updates made to original issue, based on comments from July 8th, 2019 meeting

**Comment by steveoh** [comment]
I think 1.7.2 completes this issue.
