### ISSUE TITLE
Update Database Schema

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#116]
to accommodate O-track data now received via API

**Comment by nathankota** [comment]
I will take your word for it that the schema is good to go. How can I find out if/what updates need to happen to the wikis for the [db fields](https://github.com/agrc/parole-and-probation/wiki/Database-Fields) and [lookups](https://github.com/agrc/parole-and-probation/wiki/Lookup-Data)?

**Comment by steveoh** [comment]
I would assume the client would know that best.

**Comment by nathankota** [comment]
schema built based on known data and app requirements provided by client, with no changes or additions required at this time
