### ISSUE TITLE
Filter Category- Supervision Contact

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#12]
### Summary
As a user, I would like to have a filter category called "Date Factors" that I can click an icon to expand the filters within that category, and select which filters I want to apply.

#### No attempted field contact in last
- [x] 30 days 
- [x] 60 days 
- [x] 90 days 
- [x] 180 days 
#### No successful field contact in last
- [x] 30 days 
- [x] 60 days 
- [x] 90 days 
- [x] 180 days
#### No office contact in last 
- [x] 30 days 
- [x] 60 days 
- [x] 90 days 
- [x] 180 days
#### Out of compliance
- [x] single button
- do out of compliance calculation on the full data set daily, after data updates are received
    - this calculation depends on the offender's [std_of_sprvsn](https://github.com/agrc/parole-and-probation/wiki/Lookup-Data#standard-of-supervision)

**Comment by nathankota** [comment]
Question posed to AP&P if they want to be able to do both the data range and the # days since.

**Comment by steveoh** [comment]
current mock up. labels collapse calendars
![image](https://user-images.githubusercontent.com/325813/58998045-3425ba80-87bc-11e9-8f8a-b96c76110b51.png)

**Comment by steveoh** [comment]
On mobile, do not render calendars. Use input type date

> On the Date Tab, it could be complicated to use on phone. In addition to having calendars where you have to select the date it would be nice to have box where you can just pre-select the filters you want to apply. (see attached image for more information).

**Comment by steveoh** [comment]
The 6/17 meeting made a mess of this filter area. We will need clarification before proceeding with anything here.

**Comment by nathankota** [comment]
Edits made to initial issue based on July 1 meeting input. Asked client if there is a single field they can send for last attempted field contact date.
