### ISSUE TITLE
Special Supervision filter changes

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#120]
### Issue
Using boolean `AND` in the special supervision filter diminishes the effectiveness of the `All` and `Default` filter buttons - neither return any offenders because no offenders have more than two or three special supervision. AP&P team decided on the following: 

### Solution 
(determined in accordance with AP&P team)

- [ ] Remove `All` filter/button
- [ ] Remove `Default` filter/button
- [ ] Change the `None` button text to "Clear" or some other text to describe that it removes filter selections, and that it is not a filter for offenders without any special supervisions

**Comment by steveoh** [comment]
Did you give them the pro's and con's that I listed when we discussed this? I think they will help them make an educated decision.

**Comment by steveoh** [comment]
none of the other filter types have a clear button. I vote we remove that also since it doesn't align with the rest of the filters.

**Comment by steveoh** [comment]
Is there a way to update this automation to move this to `implement done` since you can't validate until i deploy?
