### ISSUE TITLE
Project incoming data to 3857

### ISSUE THREAD

**Issue by steveoh** [agrc/parole-and-probation#121]
> They are going to continue geocoding, storing and sending lat/lon.

_Originally posted by @nathankota in https://github.com/agrc/parole-and-probation/issues/17#issuecomment-756308587_

The speed of the application will improve if the data is not reprojected on the fly.

**Comment by nathankota** [comment]
This makes more sense now. It didn't click with me that reprojection was happening on the fly - I thought it was being done before ingestion into our database. Or are coordinates being read directly from the API? (this might be an opportunity for a GitHub Discussion?)
