### ISSUE TITLE
Production Database

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#122]
order one up!

**Comment by nathankota** [comment]
@steveoh can you please help fill in the blanks for these

**Name:**
**Space required:**
**Expected growth:**
**Users:**
**Permissions for requested users:**
**SDE:** Not required

**Comment by steveoh** [comment]
@MichaelAGRC usually picks these for us. Most of the values can probably be the same from the dev db. The space can be derived from dev with the growth expectation being low.

We need a read and write user just like dev ideally with different credentials.

**Comment by MichaelAGRC** [comment]
Happy to do so.  Just need to be sure of which database I'm moving to Prod.  I'm guessing DOCOffender?  The UBusted database?

**Comment by nathankota** [comment]
I had forgotten the name but that sounds like the right one. @steveoh can you please confirm?

**Comment by steveoh** [comment]
Yes that's the name. No need to migrate the schema or data - just db and users.

**Comment by nathankota** [comment]
> Happy to do so. Just need to be sure of which database I'm moving to Prod. I'm guessing DOCOffender? The UBusted database?

@MichaelAGRC you are correct and...

> No need to migrate the schema or data - just db and users.

**Comment by MichaelAGRC** [comment]
This has been completed.  I've sent the details under other cover.
