### ISSUE TITLE
filter agent issues

### ISSUE THREAD

**Issue by steveoh** [agrc/parole-and-probation#127]
- [x] clicking on a vanity name does not deselect the me button 
	- this works in the storybook but not the app
- [x] the vanity story doesn't show the "me" button in the selected items box until toggled
- [x] the item to string value is uppercased but the search values and selected items are start cased
    - this seems to be an issue with all the combobox's we've refactored so far
- [x] when an agent is added to the filter the map extent is not updated
    - from what i can tell [queryExtent](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-layers-FeatureLayerView.html#queryExtent) returns false instead of something useful.

I haven't started to fix these issues yet. feel free to jump on em.

**Comment by stdavis** [comment]
> * the item to string value is uppercased but the search values and selected items are start cased

I don't understand what the issue is. It is passing the data back to the dispatcher without mutating it from the original format. Are you thinking that it should be start-casing it?
