### ISSUE TITLE
Export not working after toggle filters

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#135]
## Issue description
After implementing one or more toggle filters the export function does not produce any download or email results. However, if one or many toggle filters are implemented in conjunction with at least one text or select filter, the download will work. Multiple toggle filters were attempted independently of one another, and in combination. The only toggle filter I am unable to try is `Me`, because I do not have any assigned offenders.

#### Expected result
I expected: to be able to use a single toggle filter, or multiple toggle filters (without any other type of filter) then export the results as a csv download and email.

#### Actual result
Instead: The toggle filters work to limit the points on the map, but when I click the export button it turns red for a moment, or spins once, and no download or emailed file occurs. 

### Agent

- Me

### Offender

- Gender

### Location

- Region

### Supervision Contact

- Compliance
- No attempted field contact
- No successful field contact
- No office contact

### Other

- Legal Status
- Standard of Supervision

**Comment by steveoh** [comment]
This looks to be caused by some unexpected data. 

> Unhandled exception\r\nSystem.Data.DataException: Error parsing column 37 (offense_code=<null>)\r\n ---> System.ArgumentNullException: Value cannot be null.

**Comment by steveoh** [comment]
The query creation also seems to have an upper limit of 2100 items. I will look into restructuring the query to handle larger sets of offenders.

> The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.

**Comment by nathankota** [comment]
Export feature still does not seem to work with toggle filters alone or in combination with non-toggle filters.

#### Test Scenario 1:

- City = Price
- Click Export
- Export works as expected

#### Test Scenario 2:

- City = Price
- Gender = Female (toggle)
- Export did not work

#### Test Scenario 3:

- Zip = 84107
- Export works as expected

#### Test Scenario 4:

- Gender = Female (toggle)
- Region = 5 (toggle)
- Click export
- Export did not work

#### Test Scenario 5:

- Gender = Female (toggle)
- Region = 5 (toggle)
- City = St George
- Click export
- Export did not work
