### ISSUE TITLE
Active Warrant data incorrect

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#139]
All `active_warrant` data being sent as of today is `N` (no), even though Otrack contains offenders with active warrants. Reached out to _UDC-BOPP Software CR_ to look into what data they are sending for that.

**Comment by nathankota** [comment]
> We're actively resolving urgent issues from our Informix upgrade this past weekend. I will check with Trevor and get back to you.

**Comment by nathankota** [comment]
Meeting to occur with UDC DTS on Wednesday, March 10

**Comment by nathankota** [comment]
Offender endpoint has been updated to provide correct warrant data and released to production

**Comment by steveoh** [comment]
The new data should be pushed to the database with our automated tools. please check the app over the next few days to see if they show up.

**Comment by nathankota** [comment]
/remind me to check this on Friday, April 15, 2021

**Comment by nathankota** [comment]
Filter differentiates b/t active and no warrants, and testers have not indicated that it is showing faulty data, so closing.
