### ISSUE TITLE
Filter menu blank

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#141]
> Using my iphone 7. Tap the arrow to open the filter menu and I get a blank screen. 

> Today on 2/22 I was able to play with the mobile and show five agents just fine, then the screen whited out on the sixth agent I was showing and it wouldn't work.  I closed out the app several times but when I reopened it couldn't get anything more than the white screen.  

> While showing it on my iPhone 7 to more agents this morning 2/24 I paid more attention to when the screen fritzed out. I was zooming in on the map after returning to the map from a filter selection. I don't know if that was it... 
The error I get now when attempting to log back in is "Safari cannot open this page. The error was: "The operation couldn't be completed. (webkitblobresource error1.)"
Five minutes later I tried the app again and the map functionality comes up but the filter screen is just a blank white page which cannot be navigated away from.

![image](https://user-images.githubusercontent.com/15659642/109876889-8dd84480-7c2f-11eb-9582-66d52f8325bf.png)

**Comment by steveoh** [comment]
Im going to assume that this means their authenticated session ended or got mixed up. I think I will plan to add a login button or something to that screen to try to give folks a chance to authenticate again.
