### ISSUE TITLE
Increase click search radius on offender points

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#147]
Some users are having a hard tapping offender points to engage the popup on mobile.

**Submitter:** Steve Yeates
> Any way to make the offender dots larger when you hover over them or get bigger as you zoom in on the map?  With my old eyes and unsteady hand I find myself clicking several times to hit a dot on

**Comment by steveoh** [comment]
The point symbology doesn't affect the click search radius. I can increase the click search radius without changing the symbology if that is the ultimate goal. If so please update the title etc to reflect.

**Comment by nathankota** [comment]
Yes! That is the goal. Title and initial comment edited.

**Comment by nathankota** [comment]
Noticeable difference on mobile and desktop.
