### ISSUE TITLE
Filter view/layout

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#151]
**Submitter:** Steve Yeates

> When opening up the filter view from the map view on my iPhone 7 there are times when it opens up the view a ways down from the top - should it be defaulting to the top each time you switch back and forth or does it jump back to the last filter you selected?

**Comment by steveoh** [comment]
I believe it opens at the location where it was last left.

**Comment by nathankota** [comment]
Your answer may very well be all that is needed, unless they want to change the existing behavior for some reason. I will remove the enhancement label.
