### ISSUE TITLE
address start date

### ISSUE THREAD

**Issue by steveoh** [agrc/parole-and-probation#16]
there is an address start date of `datetime.datetime(1111, 11, 11, 0, 0)` which looks like bad data and should be fixed. I will handle it in code but I thought it would be good to document. (85404)

**Comment by steveoh** [comment]
So I believe this is an issue with their data using a really old date as null instead of using null. Hopefully we can get them to address this during their export.

**Comment by nathankota** [comment]
are you thinking that because datetime.datetime(1111, 11, 11, 0, 0) appears in the database quite a bit?

**Comment by nathankota** [comment]
UDC dba comments: 

> Those were from when we converted old legacy data. The old system did not force a date, so 1111-11-11 represents an unknown value in the converted data. Personally, I do not like the decision to do that; it's throughout various database tables and columns.

It sounds like those values will remain in the export.

**Comment by nathankota** [comment]
Did they change these dates in the source data, or did you deal with it in code? I don't know of a way to check/test this in the app but I will move it to validated anyway.

**Comment by steveoh** [comment]
I think this was mostly an issue with the CSV export. But now that you got me to verify it, the min address start date is very old. min: `0014-04-02` max: `2020-12-21`

We might want to get this fixed as I assume this is supposed to be `2014`.

**Comment by nathankota** [comment]
message sent to Jessica Cook about fixing the date in O-Track

**Comment by steveoh** [comment]
here is another that looks like an issue `1900-01-01`

**Comment by nathankota** [comment]
checked in with Andrew and Trevor about this today - about changing the addresses in O-Track or getting bad addresses filtered out

**Comment by steveoh** [comment]
These are dates not addresses just to be clear.

**Comment by nathankota** [comment]
> These are dates not addresses just to be clear.

Thanks for catching - comment updated.

**Comment by nathankota** [comment]
AP&P updated the dates for the following records last evening. @steveoh can you please confirm, then we can close this issue?
46222	1900-01-01
51861	1900-01-01
52022	1900-01-01
201213	0014-04-02

**Comment by steveoh** [comment]
all the dates fields look good now.
