### ISSUE TITLE
x, y spatial reference

### ISSUE THREAD

**Issue by steveoh** [agrc/parole-and-probation#17]
the current x y coordinates are in lat/lon. To map these we will prefer web mercator 3857. Would you request they use that spatial reference when geocoding?

**Comment by nathankota** [comment]
Ralph Porter contacted 5/6/19 about this. Awaiting response.

**Comment by steveoh** [comment]
Projecting is fine. I'd rather not do it on every import. so if they take care of it that is acceptable.

**Comment by nathankota** [comment]
July 31, P. Stireman indicated:
_Ralph is populating Mercator X and Y columns. I'll use these values as my X and Y._

**Comment by nathankota** [comment]
With the new API, is this an issue anymore?

**Comment by steveoh** [comment]
yes.

**Comment by nathankota** [comment]
(asked Trevor et al. if they are storing mercator x,y and if we can receive those data)
