### ISSUE TITLE
Map Application Security

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#2]
### User Story

As an administrator, I would like the application to be protected by UMD login, and I would like to be able to manage users' access. 

### Details
- [x] restrict access via UMD
- [x] site admin user management

**Comment by steveoh** [comment]
@nathankota will you answer any questions you have in here, as well as provide a list of email addresses for who should have access for testing so we can setup openam for this site in test.

**Comment by nathankota** [comment]
Contacted DOC about this, and waiting to hear back.

**Comment by nathankota** [comment]
A few more users will be added, but here's the list so far:

![image](https://user-images.githubusercontent.com/15659642/59471463-62c51600-8df8-11e9-987c-bb679486386f.png)

**Comment by steveoh** [comment]
INC1046146

**Comment by steveoh** [comment]
I sent Jessica Cook instructions on how to be an admin.

**Comment by steveoh** [comment]
I will still need to protect the map service but the stuff in this issue is complete
