### ISSUE TITLE
Define DB Schema and Build DB

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#24]
- [x] db schema
- [x] AT sql server db

**Comment by nathankota** [comment]
@steveoh is this a good place to put this? Codes for legal status and special supervision are [here](https://docs.google.com/spreadsheets/d/1rQeOxktyp-ZtM4ClQU3xDLq81NzjuOxosBVhHO1HTKA/edit#gid=902985262).

**Comment by steveoh** [comment]
Seems like it's fine. I'd probably look for it in the wiki though.

**Comment by nathankota** [comment]
https://github.com/agrc/parole-and-probation/wiki/Lookup-Data

**Comment by nathankota** [comment]
@steveoh should we close this and add a new one for the prod db when applicable?

**Comment by steveoh** [comment]
Sure
