### ISSUE TITLE
Rearrange Filter Layout

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#27]
Instead of tabs, client requests filters arranged vertically, grouped by existing categories that can be expanded/contracted to show filters within, such as:

![image](https://user-images.githubusercontent.com/15659642/59381294-4c478d80-8d18-11e9-8d78-760a24350ab3.png)

**Comment by steveoh** [comment]
I'm going to need #26 and #28 merged before I start on this.
