### ISSUE TITLE
Map Application Design

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#3]
### User Story
As a user I would like the application design to resemble the [Utah Vehicle Collisions](https://crashmapping.utah.gov/) application.

### Details
- [x] App name in header = _AP&P Field Map_
- [x] Default basemap is AGRC Lite
- [x] Additional basemap selections

![BasemapSelections](https://user-images.githubusercontent.com/15659642/54385950-77f5a180-465d-11e9-8c06-65797a42e668.JPG)

- [x] Zoom in/out widget and mouse roll to zoom
![zoom in out](https://user-images.githubusercontent.com/15659642/54386155-f4888000-465d-11e9-9345-06aef4aaffdf.JPG)

- [x] Hamburger icon on right side of header to open/close filter and other widget(s)
- [ ] Utah Dept. of Corrections and AGRC logos in lower right corner of page

**Comment by steveoh** [comment]
@nathan Do you have a corrections logo handy? Please add one here.

**Comment by nathankota** [comment]
asked DOC for logo

**Comment by steveoh** [comment]
i grabbed something from their website and am thinking of skipping the agrc/cor logos in the lower right

**Comment by nathankota** [comment]
jpg image located in https://drive.google.com/drive/u/0/folders/1agcCNTsUPOi56NLIxR907U1fsOlKJtvR

![UDC Logo recent](https://user-images.githubusercontent.com/15659642/59442410-66847880-8db7-11e9-9cf7-743bf8900829.jpg)
