### ISSUE TITLE
Extend login settings

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#39]
DOC team asked if login setting can be extended on app

**Comment by steveoh** [comment]
We will want to present this to kyle burkhardt. I'm not sure if a service now ticket is best or a chat message. I'll let you decide.

**Comment by nathankota** [comment]
Kyle Burkhardt emailed about this

**Comment by steveoh** [comment]
from Karl

> 12 hours is sufficient

7/29 meeting
