### ISSUE TITLE
Popup - Mobile Issues

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#47]
- [x] At least one agent indicated that he could not get the popup to open on a mobile device. @steveoh suggested expanding beyond 3 pixels. (could this issue have been fixed by opening up access to all offenders for testing?)

- [x] orientation of information looks like the following on Google Pixel:
![image](https://user-images.githubusercontent.com/15659642/62649100-69ac6880-b911-11e9-868a-0b7b7f5e8ace.png)

**Comment by steveoh** [comment]
Still need to do the touch sizing...
