### ISSUE TITLE
Offender Location Pop-Up UI

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#5]
### Summary
As a user, when I zoom in far enough to distinguish a single point of an offender's location, I would like to be able to click on the point to see a pop-up with offender information. I would like the information organized so that I may click to expand information below logical categories. 

### Data to show in pop-up
- [ ] offender image
- [x] gender
- [x] age
- [x] legal stat
- [x] standard of supervision
- [x] active warrant 
- [ ] alerts (highlighted, red text, or similar)
- [x] cautions (highlighted, red text, or similar)
- [x] offender name
- [x] offender number
- [x] agent name

#### Recent Contact
- [x] last field contact date
- [x] last field contact result
- [x] last office contact date

#### Contact Information
- [x] offender phone number  
- [x] street address
- [x] unit
- [x] city
- [x] zip
- [x] address type
- [x] address start date
 - [x] employer

#### Crime  
- [x] offense degree / description
- [x] supervision start date
- [x] standard of supervision
- [ ] [special supervision description](https://github.com/agrc/parole-and-probation/wiki/Lookup-Data#special-supervision)
- [x] [gang type](https://github.com/agrc/parole-and-probation/wiki/Lookup-Data#stg-type) 
- [x] [gang name](https://github.com/agrc/parole-and-probation/wiki/Lookup-Data#stg)
- [x] compliance credit

**Comment by steveoh** [comment]
I think we should prioritize these values. I'll come up with what I think it could be and let the officers argue it out.

**Comment by nathankota** [comment]
replaced by #34

**Comment by steveoh** [comment]
@nathan I see you moved this to validate active. 

I'm a little unsure how to deal with this properly since the identify implementation isn't done. It's not using the real data and quite a bit more work is required to "finish" the implementation. Do we track that with a separate task or this one, I'll let you decide.

**Comment by nathankota** [comment]
Great point. That makes sense and I'll move it back to (I'm thinking) Implement (Active)?

**Comment by steveoh** [comment]
We may want to track the UI separately from the functionality because we have the same issues with the filters.

**Comment by steveoh** [comment]
![image](https://user-images.githubusercontent.com/325813/59731195-65fa4080-9202-11e9-9df1-ab0f03f5c75a.png)

**Comment by nathankota** [comment]
Feedback from July 1 meeting, clients like the proposed layout with a few suggestions:

- [ ] add alerts (highlighted, red text, or similar) - need to be sent in data transfer
- [ ] add cautions (highlighted, red text, or similar) - need to be sent in data transfer
- [ ] if standard of supervision is null, show "no std"
- [ ] move offenses to another part of the pop-up; there may be multiple for a single offender
- [ ] move gang name and type after crime
- [ ] phone number is important, type is not; remove type
- [ ] make phone number a link that will call directly
- [ ] make address link to google map
- [ ] active warrant highlighted, red text, or similar (like alerts and cautions)
- [ ] display [special supervision description](https://github.com/agrc/parole-and-probation/wiki/Lookup-Data#special-supervision)
- [ ] display [full gang name](https://github.com/agrc/parole-and-probation/wiki/Lookup-Data#stg)
