### ISSUE TITLE
Offender Point Symbology

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#53]
Symbolize points by legal_stat_type values:
- [x] Parole = green
- [x] Probation = blue
- [x] Fugitive = red

**Comment by steveoh** [comment]
what field has fugitive?

**Comment by nathankota** [comment]
question posed to Phillip

**Comment by steveoh** [comment]
does active warrant mean fugitive?

**Comment by nathankota** [comment]
based on the definition of a fugitive and fugitive warrant, it seems like no, but will confirm with DOC staff

**Comment by nathankota** [comment]
Fugitive is indicated by the following values in the **_offender_location_** field:
FUGITIVE REG 1
FUGITIVE REG 3
FUGITIVE REG 4
FUGITIVE REG 5
FUGITIVE REG 6

**Comment by steveoh** [comment]
implemented with arcade

```js
var fugativeTypes = ['FUGITIVE REG 1',
'FUGITIVE REG 3',
'FUGITIVE REG 4',
'FUGITIVE REG 5',
'FUGITIVE REG 6',
'C-FUG-RG3',
'P-FUG-RG3'];

if (indexOf(fugativeTypes, $feature.offender_location) > -1) {
return 'FUGATIVE';
}

return $feature.legal_status;
```
