### ISSUE TITLE
Popup - Multiple Offenders at Location

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#54]
It is possible for there to be 15+ offenders at a single location. 

- [x] Show 1-5 as array with the ability to expand or scroll to see the others. 
- [x] Sort results alphabetically (A-Z) by last name. 

![image](https://user-images.githubusercontent.com/15659642/62658156-4be8fe80-b925-11e9-9eb9-fb037e6e3cf1.png)

**Comment by steveoh** [comment]
i think 
![image](https://user-images.githubusercontent.com/325813/63139118-56953a80-bf9a-11e9-9971-40a2f36e5717.png) will be a better overall approach. Hopefully they like it.

**Comment by steveoh** [comment]
closed by 19e4eac8e83a2a1c1a908a3c201ee9e0a4fd4842
