### ISSUE TITLE
csv download

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#56]
After a filter has been applied, users would like a "download" button to download a csv of the filter results. The csv should include [all attributes](https://github.com/agrc/parole-and-probation/wiki/Database-Fields) for returned offender records.

**Comment by steveoh** [comment]
This is the visible offenders when the button is clicked or all offenders matching the filter?

**Comment by nathankota** [comment]
Karl and I discussed this and he decided on _all offenders matching the filter_.

**Comment by steveoh** [comment]
ok so ignore the map extent from whatever zooming you do. :+1:

**Comment by nathankota** [comment]
Can the returned list of offenders be dynamic based on the map extent?

**Comment by steveoh** [comment]
The visible offenders, yes I think that is simple to code...

**Comment by nathankota** [comment]
Want to make sure I understand about the extent being used. Does that mean:

1. Apply filter
2. Zoom to an area of interest (e.g. a neighborhood) and there are 2 offenders matching the filter+area combination.
3. Downloadable list of offenders only contains those two offenders
4. Zoom out to municipality level and there are 10 offenders matching that filter+area combination
5. Downloadable list of offenders contains those 10 offenders

**Comment by steveoh** [comment]
✅

**Comment by nathankota** [comment]
Let's go with extent then. They can always click the full extent button to make sure they're getting the full list.

**Comment by steveoh** [comment]
@nathankota Do you think the officers would appreciate the csv being emailed to them rather than prompting them for download? It will be all ready to share with just a fwd button. It will also be a little less coding for me I think also...

**Comment by nathankota** [comment]
Interesting idea. Could they share it with more than one email or would it go directly to them since they are logged in?
