### ISSUE TITLE
Offender filter actions

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#57]
![image](https://user-images.githubusercontent.com/15659642/62724181-9c1c9b00-b9cf-11e9-9e2e-8b95f65f1b5a.png)
**start typing to get hints matching first or last name**

---

![image](https://user-images.githubusercontent.com/15659642/62724301-edc52580-b9cf-11e9-8b57-ab2a2dd49bbf.png)
**start typing to get hints for matching offender numbers**

---

![image](https://user-images.githubusercontent.com/15659642/62724366-0df4e480-b9d0-11e9-9863-3604ddb071a5.png)
**start typing to get hints for matching offender phone numbers**

---

![image](https://user-images.githubusercontent.com/15659642/62724419-2cf37680-b9d0-11e9-9048-8935873e2b0d.png)
**start typing to get hints for matching offender employer name**

**Comment by steveoh** [comment]
how do the hints work in regards to already applied filters?
