### ISSUE TITLE
Popup - Employer info

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#58]
Offenders' employer name, address, and phone have been broken into three fields. Enable phone number to link to phone call from mobile device, and address to link to google maps route.

![image](https://user-images.githubusercontent.com/15659642/62731135-bc078b00-b9de-11e9-8eb8-52ea879ae618.png)

**Comment by steveoh** [comment]
@nathankotan would you explore if the employer name should be included in the address provided to gmaps or if better result are returned by only using the address. For now I am going to use the address only and omit the employer name.

**Comment by nathankota** [comment]
I have discovered enough variation in the employer names to confirm its omission from the address provided to google maps. 

Some variations include:

- incorrect employer name (e.g. Metro Recycling vs. Rocky Mtn. Recycling)
- incomplete employer name (e.g. Coachmans Diner vs. Coachmans Diner and Pancake House)
