### ISSUE TITLE
Filter other - special_supervision

### ISSUE THREAD

**Issue by steveoh** [agrc/parole-and-probation#70]
since the `special_supervision` database field is a string of values, I need to know the order they will be applied since we are doing a string match.

For instance, if a record is `INCAR, SO-A` I need to guarantee the order of the fields no matter what order the agents input them. Currently, it is in the order that are entered. So an agent could add `SO-A` and `INCAR` and we would not find any records.

can the DOC give us a guaranteed order? It appears there is one. 

If not we will need to create another solution.

**Comment by nathankota** [comment]
waiting for feedback from Phillip

**Comment by nathankota** [comment]
@steveoh The response to my question about there being a set pattern for the data was:

_Well, not really, but sort of,  The static look-up table that maintains the special supervision codes has a serial integer as the primary key; today they start at 1 and end with 23 with no gaps.  There is also a column for a non-duplicated priority of the special supervision._

_The priority would be ideal, and second to that the serial key should work if they never changed._

_The chances of these changing is small, but possible, so I cannot guarantee the exact same order from now until the end of time._

If we ask to receive one of the two codes and order them sequentially would that work?

**Comment by steveoh** [comment]
I am not sure I follow that. Is he saying that they are using the serial integer to order them or the non-duplicated priority value to order them?

I need to know if I can match their logic for the order of those strings.

**Comment by nathankota** [comment]
Serial integer primary key is preferred for ordering. Awaiting those values from Phillip.

**Comment by nathankota** [comment]
I will add this to the wiki as well:

![image](https://user-images.githubusercontent.com/15659642/64534631-07a99f00-d2d3-11e9-9227-31c7757e58c4.png)
