### ISSUE TITLE
Token service getting bad tokens

### ISSUE THREAD

**Issue by steveoh** [agrc/parole-and-probation#72]
the response is 

```json
{"error":{"code":498,"message":"Invalid Token","details":[]}}
```

handle response and get a new token...

**Comment by steveoh** [comment]
I can't reproduce this locally. I wonder if there is something about the time zone or something on the server. I am going to decrease the token time to see if it happens more often.

**Comment by nathankota** [comment]
@steveoh Is this something that can be tested by me or users, or can I move it to validate(done)?
