### ISSUE TITLE
County and Region

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#74]
- [x] Add county field to database
- [x] Add county data for offenders with x,y from [here](https://docs.google.com/spreadsheets/d/1B59W2HEzQzzoT6smzi-Mhl_GzdGiPLX4/edit#gid=1902603187)
- [x] If desired, update region field that was calculated via spatial join for offenders that had an x,y also from [here](https://docs.google.com/spreadsheets/d/1B59W2HEzQzzoT6smzi-Mhl_GzdGiPLX4/edit#gid=1902603187)
- [ ] Wire up County filter

**Comment by steveoh** [comment]
in what order is the database field going to be in the data export @nathankota?

**Comment by nathankota** [comment]
waiting for confirmation, but pretty sure it is the last field
