### ISSUE TITLE
Add Region boundaries to map

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#77]
Add the regions as a layer on the map that can be turned on/off. 

@jacobdadams tasks:
- [x] Merge county features by region
- [x] Edit `Northern Utah Region` to be `Northern Utah` 
- [x] Layer symbology same as Jake's [region map] (https://drive.google.com/drive/u/0/folders/1agcCNTsUPOi56NLIxR907U1fsOlKJtvR)
- [x] Publish regions as hosted feature layer in AGOL

@steveoh tasks:
- [x] On Field Map, put region layer in layer list 
![image](https://user-images.githubusercontent.com/15659642/71420066-55eb6f80-2630-11ea-890b-4447edc187b3.png)

- [x] Use region numbers/name as labels 
- [x] Make regions same transparency as `UWRI Focus Areas` reference layer on the [WRI map](https://wri.utah.gov/wri/map/map.html)

**Comment by jacobdadams** [comment]
Region boundaries have been uploaded to our AGOL org at http://utah.maps.arcgis.com/home/item.html?id=ffe5276387e94b3997cc9e54a6067835 (shared publicly).

**Comment by steveoh** [comment]
I appreciate the link to the wri service as an example, but it took me ~15 minutes to find the value of .75. I ended up use .25 because I think it looks better. Let me know if you are ok with that modification.

**Comment by nathankota** [comment]
Transparency of 0.25 looks good, thank you.
