### ISSUE TITLE
Filter Category - Agent

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#8]
### Summary
As a user, I would like to have a filter category called "Agent" that I can click an icon to expand the filters within that category, and select which filters I want to apply.

### Agent 
- [x] My offenders (offenders assigned to me, as a logged-in agent)
    - agent_name
- [ ] Search Agent (offenders assigned to other agents)
    - agent_name
- [ ] Search Supervisor (offenders returned by agents' supervisors)
    - supervisor_name

**Comment by steveoh** [comment]
are these supposed to be presented as checkboxes or free text?

can you select or type into more than one of these at a time?

**Comment by nathankota** [comment]
The second seems more right, but I'm not sure how many agents, supervisors, or offenders (by agent) there are, which may influence checkboxes vs free text. I will ask. I will also find out if they want/need to enter into more than one at a time. If so, that might get tricky because of nested relationships of supervisors to agents to offenders (?).
