### ISSUE TITLE
Special Supervision - Multiple Match

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#84]
Related to #81 
Agent Feedback:

_it would be beneficial to return all (offenders) that show a match of the special supervision filter, even if they have more than one special supervision status_

**Comment by nathankota** [comment]
> I think the defaults for the special supervision don't make sense in the AND scenario

> some of them seem mutually exclusive and i don't see any offender with all of them so unsure why it's a default

> ALL doesn't make sense either with the ANDs

> so i think at some point the default should be updated or removed and the same for all unless they like the way it adds items and they can simply click to remove items without having to type

**Comment by steveoh** [comment]
are you planning to address these in a new issue?

**Comment by nathankota** [comment]
yes, I'll remove the comment from here and put it in a new issue - was just wanting to store the comment somewhere as I tested the app. I understand it better now.

**Comment by nathankota** [comment]
replaced by #120
