### ISSUE TITLE
Dynamic Filters

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#87]
Apply filters dynamically as they are selected. This negates the need for an _Apply_ button, but requires a _Reset_ or _Clear_ button to remove filters.

**Comment by steveoh** [comment]
I'm going to need a little bit of scott to get me over a little hurdle with this one.

**Comment by nathankota** [comment]
Sounds good - whatever time works well for you two to coordinate.

**Comment by steveoh** [comment]
closed with 54b831e12e0a3fe416ecb37427e832cc89e89266
