### ISSUE TITLE
Filter Category - Location

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#9]
### Summary
As a user, I would like to have a filter category called "Location" that I can click an icon to expand the filters within that category, and select which filters I want to apply.

#### Near Me
 - [ ] my current location. or
 - [ ] drop a point on map, or
 - [ ] enter location (address) 
 - [ ] ability to buffer locations
#### City
  - [x] city (db field)
#### Zip
  - [x] zip
  - db contains all null values
#### Region
  - [x] region_id
  - db contains all null values
#### County
  - [ ] spatial query
  - (not stored in database)
~~**Address Type**~~
 ~~- addr_typ_cd~~

**Comment by steveoh** [comment]
can you define `selected location` and `entered location`

**Comment by steveoh** [comment]
current mock up

![image](https://user-images.githubusercontent.com/325813/58997991-017bc200-87bc-11e9-9215-4d87ef2b4ced.png)

**Comment by nathankota** [comment]
Will confirm with client on Monday, but I believe selected location is dropping a point on the map, and an input location is entering (searching) a valid address. Keep options for city, zip, county. If a specific point is dropped or determined by an input address or current location, they want to return offenders nearby. Perhaps there should be static buffer/radius selections to choose from. Again, this will be confirmed with client. Apologies for the uncertainty.

**Comment by steveoh** [comment]
great experiences to learn from moving forward 🚀

**Comment by nathankota** [comment]
No doubt. I'm learning that every client is very different in their participation.

**Comment by steveoh** [comment]
I think we should preprocess the value for county so it is like city. No sense in complicating things

**Comment by nathankota** [comment]
County will eventually be provided in data transfer, after DOC address fixing and geocoding process is complete.

**Comment by nathankota** [comment]
9/5 meeting notes:

- Move Current, Select, and Address onto map
![image](https://user-images.githubusercontent.com/15659642/64535070-dd0c1600-d2d3-11e9-9cf1-285008537d28.png)

- set default zoom to negative 5 (zoom level 16?)

**Comment by steveoh** [comment]
I created a new issue for this as it seems new.
