### ISSUE TITLE
Post-filter map scale

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#90]
When filter is applied, map scale should be the same as the (new) default zoom level.

current:

![image](https://user-images.githubusercontent.com/15659642/73369374-c14be100-426f-11ea-9406-4e85861d34a9.png)

expected:

![image](https://user-images.githubusercontent.com/15659642/73373559-0ecb4c80-4276-11ea-906e-cf371e0d50e3.png)

**Comment by steveoh** [comment]
That commit did not fix this. Depending on the mobile view, the map width is less than 50px so the zooming results is very far out. I need to think of a new solution to this and it might require a foundational layout refactor.
