### ISSUE TITLE
Can't exit "No offender" message

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#91]
On android device (google pixel), tap screen once in location where there is no offender and the following message appears with no way to close the message and get back to the filter panel...

![image](https://user-images.githubusercontent.com/15659642/73369832-7d0d1080-4270-11ea-8b8b-663b7a5774ec.png)

However, on another user's phone (iphone 7, I believe), they see an `x` to close the message, but when it is tapped it returns a blank screen...

![image](https://user-images.githubusercontent.com/15659642/73370006-c5c4c980-4270-11ea-8b84-7d58dd5581a9.png)

followed by...

![image](https://user-images.githubusercontent.com/15659642/73370040-d412e580-4270-11ea-93f7-59b3ee44883d.png)

**Comment by steveoh** [comment]
On desktop and I assume on mobile, the UX is to click the blue icon to hide the pane. Does clicking the blue icon not hide the pane? 

![image](https://user-images.githubusercontent.com/325813/73406833-a3ed3600-42b4-11ea-9695-855086f9a0b8.png)

**Comment by steveoh** [comment]
This is an issue on desktop as well as mobile. Is adding a close button under the message an acceptable solution?

**Comment by nathankota** [comment]
> On desktop and I assume on mobile, the UX is to click the blue icon to hide the pane. Does clicking the blue icon not hide the pane?
> 


It does hide the pane but does not clear that message (at least on mobile)

**Comment by steveoh** [comment]
This looks like the android phone/chrome browser is rendering the page correctly and is not cut off. I'm thinking that you had the address bar active or some action to expand it. My vote is to close issue #93
