### ISSUE TITLE
Geocode widget behavior

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#92]
- [ ] Users would like for point to appear when address is found, like on desktop
 - this may already occur, but obscured by the search pane?
- [ ] Need a way to collapse the geolocate pane
 - If user taps outside of pane on map, the "No offenders at click location" message appears #91 
![image](https://user-images.githubusercontent.com/15659642/73394386-c6725580-429a-11ea-8667-c8b079ee2bd4.png)

**Comment by steveoh** [comment]
Is it acceptable to hide the geolocation widget with a close button and after a successful geocode?

**Comment by nathankota** [comment]
I like that, or an 'x'

**Comment by steveoh** [comment]
I can't easily hide the after successful geocode part so i'm going to add a close button...

**Comment by nathankota** [comment]
"x" in corner of search pane allows user to close it
