### ISSUE TITLE
Left panel access obscured by header

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#93]
The arrow to open the left panel (and a little of the layer widget) is obscured by the device header, which inhibits access to the left panel - this was noticed after implementing the geolocate widget:

![image](https://user-images.githubusercontent.com/15659642/73395536-f6225d00-429c-11ea-8bf9-dcc677ebfa71.png)

**Comment by steveoh** [comment]
this doesn't happen in ios safari or ios chrome. I'm hesitant to reposition the items for one browser. Can we get some more android users to look into this?

**Comment by nathankota** [comment]
Interesting. Yes, will do.

**Comment by nathankota** [comment]
Limited testing by users, but this only seems to be a problem for me.
