### ISSUE TITLE
Offender legend

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#95]
Add a legend for the three offender point colors below the download widget. #53

**Comment by steveoh** [comment]
how about this way? 

![image](https://user-images.githubusercontent.com/325813/73694988-73334500-4696-11ea-97cf-aba94cfb4537.png)

**Comment by nathankota** [comment]
**Note:** On mobile need to add the site to one's home screen so it acts more like an app, the header doesn't appear, and won't crowd-out the legend at the bottom.
